# File: deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-sb-deployment
  labels:
    app: java-sb-app
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: java-sb-app
  template:
    metadata:
      labels:
        app: java-sb-app
    spec:
      containers:
      - name: java-sb-container
        image: 2023mt03187/java-sb-app
        ports:
        - containerPort: 8000
---
# Nodeport service to expose the application
apiVersion: v1
kind: Service
metadata:
  name: java-sb-service
  namespace: default
spec:
  selector:
    app: java-sb-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000 
  type: NodePort
